spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
    open-in-view: false
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234

jwt:
  secret: your-256-bit-secret-key-here-must-be-at-least-32-characters
  expiration: 600000        # 10 minutes in milliseconds
  refresh-expiration: 86400000  # 24 hours in milliseconds

file:
  upload:
    path: ${user.home}/uploads/board